### ISSUE TITLE
Stereo configuration inconsistency

### ISSUE THREAD

**Issue by MherMatevosyan** [coleygroup/rdcanon2024#2]
Hi,

Thank you for your work. While canonicalizing templates several of them behave strangely. For example

`template = '[C&H2&D1&+0:1]=[C&H1&D2&+0:2]-[C:3]=[O&D1&H0:4]>>[O&D1&H0:4]=[C:3]-[C@&H1&D3&+0:2]'`
`canon_template = canon_reaction_smarts(template)`

gives 
`'[O;D1;H0]=[C]-[C;H1;D2;+0]=[C;H2;D1;+0]>>[O;D1;H0]=[C]-[C@@;D3;H1;+0]'`

which has reversed stereo. After applying the function again the stereo changes again. 
`canon_reaction_smarts(canon_template)`

gives 
`'[O;D1;H0]=[C]-[C;H1;D2;+0]=[C;H2;D1;+0]>>[O;D1;H0]=[C]-[C@;D3;H1;+0]'`

And after reapplying it switches again
`canon_reaction_smarts(canon_reaction_smarts(canon_template))`

gives
`'[O;D1;H0]=[C]-[C;H1;D2;+0]=[C;H2;D1;+0]>>[O;D1;H0]=[C]-[C@@;D3;H1;+0]'`

and so on...

Is there a way to enforce the canonicalization algorithm to keep the original chirality?

**Comment by b-mahjour** [comment]
Hello, thank you, and thanks for explaining your perceived issue!

While there are rare edge case inconsistencies with chirality, particularly with cis/trans configurations and chiral tags near rings, I do not believe this is one of them. 

In the example you have provided, the SMARTS template you are trying to canonicalize is not correctly specified. The carbon with seemingly emergent stereochemistry (atom map number 2) is fully specified "C=[CH1:2]-C", and despite specifying "D3" in your product, the template contains no substituent to add into that carbon. Thus it is virtually impossible for that template to be applied to any input substrate and create a chiral center. 

Have you attempted to try using the original template to see if it is behaving in the way you expect?

As a side note, the chiral tags @ and @@ define the 3D tetrahedral orientation of the following tokens in the line notation, and thus should not be specified in the final token of a SMARTS template.

**Comment by MherMatevosyan** [comment]
Thanks for your answer @b-mahjour . Now I see the problem with my template. I have checked the original template and you are correct the original template behaves as expected. Yup, the chiral tag in the final token should be removed, thanks for the help!
